  - name: Download get-pip.py from {{ get_pip_url }}
    get_url:
      url: "{{ get_pip_url }}"
      dest: /tmp/get-pip.py
    tags: install-pip

  - name: Create constraints file for {{ pip_version }} {{ setuptools_version }}
    copy:
      dest: "/tmp/constraints.txt"
      content: |
        {{ pip_version }}
        {{ setuptools_version }}


  - name: Install pip version {{ pip_version }} {{ setuptools_version }}
    shell: "{{ item }} /tmp/get-pip.py -c /tmp/constraints.txt pip setuptools"
    become: True
    with_items:
      - python3
    tags: install-pip
